/**********************************************************************************************************************
 * File Name    : ui_artwork.c
 * Description  : The pictures, the expression table and the picture lookup.
 *
 * New file. It holds three things: the seven whole faces, the eight gesture pictures, and the
 * table that says which face stands for which expression.
 *
 * UPDATED 2026-08-21: the eight gesture pictures are REAL now. They come from
 * art_gestures.c, generated by tools\make_gesture_art.py from the five files the user supplied
 * in assets\hand_gestures. The drawn placeholders stay in this file as the fallback for
 * APP_DEGRADE_EXTERNAL mode.
 *
 * Not copied from sample_code. The drawing calls are the ones the vision fork already makes:
 * d2_setblitsrc and d2_blitcopy for a picture (src\display_layer\detection_screen_mipi.c:113
 * and :116), d2_rendercircle and d2_renderline for the shapes (:164 and :190), d2_setcolor and
 * d2_setalpha for the colour and the transparency (src\display_layer\display_layer.c:58).
 *
 * THE ONE CALL THAT NEITHER FORK USES is the filled rectangle. It is
 *   D2_EXTERN d2_s32 d2_renderbox( d2_device *handle, d2_point x1, d2_point y1,
 *                                  d2_width w, d2_width h );
 * at ra\tes\dave2d\inc\dave_driver.h:599. The name and the four arguments above are read from
 * the drawing engine's own header, not guessed. Its coordinates are in sixteenths of a pixel,
 * like every other d2_render call in this project. The goodbye fade uses the same call.
 *********************************************************************************************************************/

#include <stdint.h>
#include <string.h>

#include "hal_data.h"

#include "art_faces.h"
#include "art_gestures.h"
#include "bg_font_18_full.h"
#include "display_layer.h"
#include "ui_artwork.h"

/**********************************************************************************************************************
 * Macro definitions
 *********************************************************************************************************************/

/* Every d2_render call in this project takes sixteenths of a pixel. */
#define UI_FX(v)              ((d2_point) (((int32_t) (v)) << 4))
#define UI_FXW(v)             ((d2_width) (((int32_t) (v)) << 4))

/* The placeholder is drawn in plain white on the black zone, so it reads at booth distance and
 * needs no artwork of its own. 24-bit red-green-blue, as d2_setcolor takes it. */
#define UI_PLACEHOLDER_COLOR  (0x00FFFFFF)

/* Line thickness of the placeholder outline and of the shapes inside it. */
#define UI_PLACEHOLDER_LINE   (3)
#define UI_HINT_LINE          (2)

/* The label under a 384 x 384 placeholder is at the sample's own text scaling; the label inside
 * a 96 x 96 hint icon has to be small enough to fit five characters across 96 pixels. */
#define UI_LABEL_SCALING      (1.0f)
#define UI_HINT_LABEL_SCALING (0.5f)

/* The size of a throw picture and of a hint icon, in pixels. */
#define UI_THROW_W            (384)
#define UI_THROW_H            (384)
#define UI_HINT_W             (96)
#define UI_HINT_H             (96)

/**********************************************************************************************************************
 * The Stage 1 face table: one row per expression.
 *
 * Seven files cover twelve expressions, so several expressions share a file. The reason for
 * each choice is kept beside its row, because those choices were argued and should not be
 * quietly re-decided by a later reader.
 *********************************************************************************************************************/
static const art_face_id_t g_expr_face[EXPR_COUNT] =
{
    [EXPR_STILL]     = ART_FACE_NEUTRAL,    /* open eyes, flat mouth: the only straight mouth  */
    [EXPR_IDLE]      = ART_FACE_ATTENTIVE,  /* a soft closed smile invites a child closer      */
    [EXPR_HAPPY]     = ART_FACE_EAGER,      /* the clearest "hello" of the seven               */
    [EXPR_ASKING]    = ART_FACE_NEUTRAL,    /* the waiting face. Shared with EXPR_STILL, which
                                             * is safe because the two never follow each other */
    [EXPR_EAGER]     = ART_FACE_EAGER,      /* anticipation during 3 2 1                       */
    [EXPR_EXCITED]   = ART_FACE_EXCITED,    /* both fists up, the moment before a throw        */
    [EXPR_PLEASED]   = ART_FACE_EAGER,      /* pleased is built from the same two parts as
                                             * happy, so it takes the same file                */
    [EXPR_CONSOLING] = ART_FACE_ATTENTIVE,  /* no sad face exists. The gentle closed smile is
                                             * the one file that cannot read as celebrating    */
    [EXPR_TELLING]   = ART_FACE_CURIOUS,    /* the only storyteller pose of the seven          */
    [EXPR_PUZZLED]   = ART_FACE_THINKING,   /* hand on the chin, an uncertain mouth            */
    [EXPR_WAVING]    = ART_FACE_FAREWELL,   /* the only raised waving hand                     */
    [EXPR_SORRY]     = ART_FACE_THINKING,   /* "something is wrong and I am working on it".
                                             * Shared with EXPR_PUZZLED, which is safe because
                                             * puzzled is a 2.5 second notice and sorry sits
                                             * under a failure message with LED3 on            */
};

/**********************************************************************************************************************
 * Private global variables and functions
 *********************************************************************************************************************/

/* One ui_image_t per expression, filled once by ui_art_init_tables(). It is not const, because
 * the pixel pointers come from art_face_table, and at Stage 2 the same entries take the parts
 * instead. */
static ui_image_t g_face_img[EXPR_COUNT];

/* The same arrangement for the three throw pictures and the five hint icons, and for the same
 * reason: the pixel pointers come from the const tables below and are dropped when the artwork
 * is not available. Ten rows of ui_image_t, so this costs 120 bytes of RAM. */
static ui_image_t g_throw_img[GESTURE_COUNT];
static ui_image_t g_hint_img[GESTURE_COUNT];

static bool       g_tables_ready = false;

/* False when the Octo-SPI never opened, so the seven face arrays hold nothing
 * (APP_DEGRADE_EXTERNAL). ui_init sets it. */
static bool       g_art_available = true;

/* The name each expression prints inside its placeholder when the artwork is not there. Same
 * order as expr_t. */
static const char * const g_expr_label[EXPR_COUNT] =
{
    [EXPR_STILL]     = "STILL",
    [EXPR_IDLE]      = "IDLE",
    [EXPR_HAPPY]     = "HAPPY",
    [EXPR_ASKING]    = "ASKING",
    [EXPR_EAGER]     = "EAGER",
    [EXPR_EXCITED]   = "EXCITED",
    [EXPR_PLEASED]   = "PLEASED",
    [EXPR_CONSOLING] = "SORRY YOU LOST",
    [EXPR_TELLING]   = "TELLING",
    [EXPR_PUZZLED]   = "PUZZLED",
    [EXPR_WAVING]    = "BYE",
    [EXPR_SORRY]     = "SORRY",
};

/**********************************************************************************************************************
 * The three throw pictures and the five hint icons. THE REAL PICTURES ARE HERE (2026-08-18).
 *
 * Until then all eight were drawn placeholders, because no picture files existed. The user
 * supplied five PNG files in assets\hand_gestures on 2026-08-18, tools\make_gesture_art.py
 * turned them into src\display_layer\art_gestures.c, and the pointers went into the pixels
 * field of these rows. NO SCREEN CODE CHANGED.
 *
 * ROCK, PAPER AND SCISSORS ARE THE SAME THREE HAND SHAPES AS THREE OF THE HINTS. That is the
 * team leader's decision of 2026-08-21: the game's throws ARE those hand shapes. Each of the
 * three is a SEPARATE array at each size, 384 x 384 and 96 x 96, because ui_art_draw blits 1:1
 * and nothing is scaled on the board.
 *
 * THE LABELS STAY, all eight of them. ui_art_draw only reads a label when pixels is NULL, and
 * that still happens: APP_DEGRADE_EXTERNAL mode calls ui_art_set_available(false) when the
 * Octo-SPI never opened, and then these arrays hold whatever the SDRAM happened to hold. The
 * labels are the fallback for that run, and they are also how ui_draw_placeholder picks which
 * simple shape to draw.
 *
 * THE TWO TABLES BELOW ARE CONST AND ARE NEVER MODIFIED. ui_art_init_tables() copies them into
 * the two working tables above, dropping the pixel pointers when the artwork is not available -
 * exactly the way the seven faces are already handled. Keeping the pointers in a const table
 * means turning the artwork back on can restore them; nulling them in place could not.
 *********************************************************************************************************************/
static const ui_image_t g_throw_art[GESTURE_COUNT] =
{
    [GESTURE_FIST]        = { art_gesture_throw_fist,    UI_THROW_W, UI_THROW_H, "ROCK"     },
    [GESTURE_OPEN_PALM]   = { art_gesture_throw_open,    UI_THROW_W, UI_THROW_H, "PAPER"    },
    [GESTURE_VICTORY]     = { art_gesture_throw_victory, UI_THROW_W, UI_THROW_H, "SCISSORS" },

    /* Not throws, so no picture is generated for them. They are here so the table has one row
     * per gesture_t value and the lookup needs no range test of its own; the demo never asks for
     * them, and if it ever did it would get the placeholder. */
    [GESTURE_THUMBS_UP]   = { NULL,                      UI_THROW_W, UI_THROW_H, "UP"       },
    [GESTURE_THUMBS_DOWN] = { NULL,                      UI_THROW_W, UI_THROW_H, "DOWN"     },
};

static const ui_image_t g_hint_art[GESTURE_COUNT] =
{
    [GESTURE_OPEN_PALM]   = { art_gesture_hint_open,        UI_HINT_W, UI_HINT_H, "PALM" },
    [GESTURE_FIST]        = { art_gesture_hint_fist,        UI_HINT_W, UI_HINT_H, "FIST" },
    [GESTURE_THUMBS_UP]   = { art_gesture_hint_thumbs_up,   UI_HINT_W, UI_HINT_H, "UP"   },
    [GESTURE_THUMBS_DOWN] = { art_gesture_hint_thumbs_down, UI_HINT_W, UI_HINT_H, "DOWN" },
    [GESTURE_VICTORY]     = { art_gesture_hint_victory,     UI_HINT_W, UI_HINT_H, "V"    },
};

/* Asked for by a caller that has nothing to show. Drawing it is a no-operation. */
static const ui_image_t g_no_img = { NULL, 0U, 0U, NULL };

static void ui_art_init_tables(void);
static void ui_draw_label(const ui_image_t * img, int x, int y);
static void ui_draw_outline(int x, int y, int w, int h, int thickness);
static void ui_draw_placeholder(const ui_image_t * img, int x, int y);

/**********************************************************************************************************************
 * Fill the face table the first time anything asks for a face.
 *
 * It is done here rather than in a start-up function because ui_artwork has no start-up step of
 * its own in the start-up order, and because the seven arrays are only readable after the
 * .sdram_from_ospi0_cs1 copy, which the start-up code runs long before the first frame.
 *********************************************************************************************************************/
static void ui_art_init_tables(void)
{
    if (g_tables_ready)
    {
        return;
    }

    for (uint32_t e = 0U; e < (uint32_t) EXPR_COUNT; e++)
    {
        g_face_img[e].pixels = g_art_available ? art_face_table[g_expr_face[e]] : NULL;
        g_face_img[e].w      = (uint16_t) ART_FACE_W;
        g_face_img[e].h      = (uint16_t) ART_FACE_H;
        g_face_img[e].label  = g_expr_label[e];
    }

    /* The same for the eight gesture pictures. The row is copied whole, so the size and the
     * label always come from the const table; only the pixel pointer is decided here. */
    for (uint32_t g = 0U; g < (uint32_t) GESTURE_COUNT; g++)
    {
        g_throw_img[g]        = g_throw_art[g];
        g_throw_img[g].pixels = g_art_available ? g_throw_art[g].pixels : NULL;

        g_hint_img[g]         = g_hint_art[g];
        g_hint_img[g].pixels  = g_art_available ? g_hint_art[g].pixels : NULL;
    }

    g_tables_ready = true;
}

void ui_art_set_available(bool ok)
{
    g_art_available = ok;

    /* Build the table again, because it may already have been built with the other answer. */
    g_tables_ready = false;
    ui_art_init_tables();

#if (BSP_CFG_DCACHE_ENABLED == 1)
    /* Artwork that the drawing engine reads as a blit source has to be cleaned out of the data
     * cache before d2_blitcopy, exactly as the camera picture is cleaned in ui_screen.c. The
     * seven face arrays are written into SDRAM by the reset copy of .sdram_from_ospi0_cs1, and
     * anything still sitting dirty in the processor's data cache is invisible to the drawing
     * engine, which reads SDRAM over the bus. The symptom would look like corrupt artwork,
     * not like a cache bug.
     *
     * ONCE, not per frame: the arrays are const and only the reset copy ever writes them, so
     * ui_init()'s single call to this function is the right place.
     *
     * Each array is cleaned on its own. They are all in the same output section, but nothing in
     * the design promises they are contiguous, and one call per array costs nothing here. */
    if (ok)
    {
        for (uint32_t f = 0U; f < (uint32_t) ART_FACE_COUNT; f++)
        {
            SCB_CleanDCache_by_Addr((void *) art_face_table[f],
                                    (int32_t) (ART_FACE_W * ART_FACE_H * (int) sizeof(uint16_t)));
        }

        /* THE EIGHT GESTURE PICTURES NEED EXACTLY THE SAME ONE-TIME CLEAN (2026-08-21). They
         * reached SDRAM by the same reset copy and the drawing engine reads them over the same
         * bus, so leaving them out would show corrupt artwork and look like anything but a cache
         * bug. The const tables are used, not the working ones, because the clean has to happen
         * whether or not a row is currently switched on, and the loop skips the two throw rows
         * that have no picture. */
        for (uint32_t g = 0U; g < (uint32_t) GESTURE_COUNT; g++)
        {
            if (NULL != g_throw_art[g].pixels)
            {
                SCB_CleanDCache_by_Addr((void *) g_throw_art[g].pixels,
                                        (int32_t) ((int) g_throw_art[g].w * (int) g_throw_art[g].h *
                                                   (int) sizeof(uint16_t)));
            }

            if (NULL != g_hint_art[g].pixels)
            {
                SCB_CleanDCache_by_Addr((void *) g_hint_art[g].pixels,
                                        (int32_t) ((int) g_hint_art[g].w * (int) g_hint_art[g].h *
                                                   (int) sizeof(uint16_t)));
            }
        }
    }
#endif
}

/**********************************************************************************************************************
 * The three lookups.
 *********************************************************************************************************************/

const ui_image_t * ui_art_face(expr_t e)
{
    ui_art_init_tables();

    if (e >= EXPR_COUNT)
    {
        /* A caller with no expression to show. The failure face is the honest answer,
         * because that is what a wrong value here means. */
        e = EXPR_SORRY;
    }

    return &g_face_img[e];
}

const ui_image_t * ui_art_throw(gesture_t t)
{
    ui_art_init_tables();

    if (t >= GESTURE_COUNT)
    {
        return &g_no_img;
    }

    return &g_throw_img[t];
}

const ui_image_t * ui_art_hint(gesture_t g)
{
    ui_art_init_tables();

    if (g >= GESTURE_COUNT)
    {
        return &g_no_img;
    }

    return &g_hint_img[g];
}

/**********************************************************************************************************************
 * Draw the label centred inside the picture rectangle.
 *
 * A 384 x 384 placeholder puts its label under the shape; a 96 x 96 hint icon puts it in the
 * middle, at half scaling, because five characters do not fit across 96 pixels otherwise.
 *********************************************************************************************************************/
static void ui_draw_label(const ui_image_t * img, int x, int y)
{
    float    scaling;
    uint32_t text_w;
    int      text_x;
    int      text_y;

    if (NULL == img->label)
    {
        return;
    }

    scaling = (img->w >= UI_THROW_W) ? UI_LABEL_SCALING : UI_HINT_LABEL_SCALING;

    /* Measured from the real glyph widths, never from a character count
     * (bg_font_18_full.c, bg_font_18_text_width). */
    text_w = bg_font_18_text_width(img->label, scaling);
    text_x = x + (((int) img->w - (int) text_w) / 2);

    if (img->w >= UI_THROW_W)
    {
        /* Under the shape, inside the bottom quarter of the box. */
        text_y = y + (int) img->h - 70;
    }
    else
    {
        /* The 22-pixel cell at half scaling is 11 pixels tall. */
        text_y = y + (((int) img->h - 11) / 2);
    }

    if (text_x < x)
    {
        text_x = x;
    }

    print_bg_font_18(d2_handle, (d2_point) text_x, (d2_point) text_y, scaling, (char *) img->label);
}

/**********************************************************************************************************************
 * A hollow rectangle of the given thickness, drawn as four filled boxes.
 *********************************************************************************************************************/
static void ui_draw_outline(int x, int y, int w, int h, int thickness)
{
    d2_renderbox(d2_handle, UI_FX(x),                 UI_FX(y),                 UI_FXW(w),         UI_FXW(thickness));
    d2_renderbox(d2_handle, UI_FX(x),                 UI_FX(y + h - thickness), UI_FXW(w),         UI_FXW(thickness));
    d2_renderbox(d2_handle, UI_FX(x),                 UI_FX(y),                 UI_FXW(thickness), UI_FXW(h));
    d2_renderbox(d2_handle, UI_FX(x + w - thickness), UI_FX(y),                 UI_FXW(thickness), UI_FXW(h));
}

/**********************************************************************************************************************
 * The placeholder: an outline of the picture's own w by h, a simple shape inside it, and the
 * label.
 *
 * HOW THE SHAPE IS CHOSEN, and why it is done this way. ui_image_t has four fields and none of
 * them can carry a shape, but each of the eight missing pictures needs a different one. Rather
 * than add a fifth field to the structure, the shape is read from the label, which is the one
 * field that already tells the pictures apart. The rule is written out below, so it can be read
 * at a glance.
 *
 * UPDATED 2026-08-21. The real pictures arrived, so in a normal run pixels is never NULL and
 * none of this is reached. IT IS STILL LIVE CODE, in two cases: APP_DEGRADE_EXTERNAL mode,
 * where ui_art_set_available(false) drops every pixel pointer; and the two rows of the throw
 * table that are not throws and have no picture.
 *
 * The four shapes are:
 *    ROCK      a filled circle
 *    PAPER     a plain rectangle outline
 *    SCISSORS  two crossed lines
 *    anything else (the five 96 x 96 hint icons) an outlined square with the short name inside
 *********************************************************************************************************************/
static void ui_draw_placeholder(const ui_image_t * img, int x, int y)
{
    const int w = (int) img->w;
    const int h = (int) img->h;

    if ((0 == w) || (0 == h))
    {
        return;
    }

    d2_setcolor(d2_handle, 0, (d2_color) UI_PLACEHOLDER_COLOR);

    /* The outline of the picture's own size, in every case. */
    ui_draw_outline(x, y, w, h, (w >= UI_THROW_W) ? UI_PLACEHOLDER_LINE : UI_HINT_LINE);

    if (NULL != img->label)
    {
        if (0 == strcmp(img->label, "ROCK"))
        {
            /* A filled circle: width 0 means filled, as the skeleton dots already do
             * (detection_screen_mipi.c:164). */
            d2_rendercircle(d2_handle,
                            UI_FX(x + (w / 2)), UI_FX(y + (h / 2) - 30),
                            UI_FXW(w / 5), UI_FXW(0));
        }
        else if (0 == strcmp(img->label, "PAPER"))
        {
            /* A second, smaller rectangle outline inside the first. */
            ui_draw_outline(x + (w / 4), y + (h / 5), w / 2, h / 2, UI_PLACEHOLDER_LINE);
        }
        else if (0 == strcmp(img->label, "SCISSORS"))
        {
            const int x1 = x + (w / 3);
            const int x2 = x + ((w * 2) / 3);
            const int y1 = y + (h / 5);
            const int y2 = y + ((h * 3) / 5);

            d2_renderline(d2_handle, UI_FX(x1), UI_FX(y1), UI_FX(x2), UI_FX(y2),
                          UI_FXW(UI_PLACEHOLDER_LINE), 0);
            d2_renderline(d2_handle, UI_FX(x2), UI_FX(y1), UI_FX(x1), UI_FX(y2),
                          UI_FXW(UI_PLACEHOLDER_LINE), 0);
        }
        else
        {
            /* The five hint icons: the outline above is the whole shape. */
        }
    }

    ui_draw_label(img, x, y);
}

/**********************************************************************************************************************
 * Draw one picture.
 *********************************************************************************************************************/
void ui_art_draw(const ui_image_t * img, int x, int y, uint8_t alpha)
{
    if (NULL == img)
    {
        return;
    }

    d2_setalpha(d2_handle, (d2_alpha) alpha);

    if (NULL != img->pixels)
    {
        /* A real picture: the same 1:1 blit the camera image uses
         * (detection_screen_mipi.c:113 and :116). Source pitch equals source width. */
        d2_setblitsrc(d2_handle, (void *) img->pixels,
                      (d2_s32) img->w, (d2_s32) img->w, (d2_s32) img->h, d2_mode_rgb565);

        d2_blitcopy(d2_handle,
                    (d2_s32) img->w, (d2_s32) img->h,        /* source width and height   */
                    (d2_blitpos) 0, (d2_blitpos) 0,          /* source position           */
                    UI_FXW(img->w), UI_FXW(img->h),          /* destination width, height */
                    UI_FX(x), UI_FX(y),                      /* destination position      */
                    d2_tm_filter);
    }
    else
    {
        ui_draw_placeholder(img, x, y);
    }

    /* PUT IT BACK. d2_setalpha is global drawing state and everything drawn after this call
     * would inherit the transparency. */
    d2_setalpha(d2_handle, (d2_alpha) 0xff);
}
