/*
* Copyright (c) 2020 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/**********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : .
 **********************************************************************************************************************/

#include "hal_data.h"
#include "common_util.h"

#include "application_config.h"
#if defined(REQUIRE_OSPI_OPEN)
#include "ospi_b_ep.h"
#endif

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/* The start-up Octo-SPI result. NOT static: file-scope
 * static in C gives internal linkage, and src\tasks\task_ui.c, task_ai.c and task_story.c all
 * read it. Declared extern in src\common_util.h. FSP_SUCCESS is 0, so a board that never
 * reaches the hook still reads as success; the hook always runs before main. */
volatile fsp_err_t g_startup_ospi_err = FSP_SUCCESS;

/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* Start micro T-Kernel 3.0. It never returns - the kernel runs its own
     * initial task, which calls usermain() in src/app_main.c.
     * The local declaration is the form the BSP2 manual prescribes:
     * ref_docs/bsp2_ra_fsp_jp.md section 4.2.3, lines 702-703.
     *
     * was: an empty body with the comment "Do nothing. This function will not be
     * called in RTOS enabled project." Under FreeRTOS the FSP generator produced an
     * RTOS main() that started the scheduler and never called hal_entry(). With
     * BSP_CFG_RTOS 0 the generated ra_gen/main.c calls hal_entry() instead, so this
     * is now the only place the kernel can be started from. */
    void knl_start_mtkernel(void);
    knl_start_mtkernel();
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses the event that is
 * called right before main() to set up the pins.
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_IOPORT_Open (&IOPORT_CFG_CTRL, &IOPORT_CFG_NAME);

        /* In order to prevent the parallel graphics panel from power-on-reset fail, */
        /* make a delay of the signal output including initial level assertion as a workaround. */
        R_BSP_SoftwareDelay(100, BSP_DELAY_UNITS_MILLISECONDS);
        R_IOPORT_PinsCfg(&IOPORT_CFG_CTRL, &g_bsp_pin_cfg_glcd);

#if BSP_CFG_SDRAM_ENABLED
        /* Setup SDRAM and initialize it. Must configure pins first. */
        R_BSP_SdramInit(true);
#endif

#if defined(REQUIRE_OSPI_OPEN)
        fsp_err_t err = ospi_b_init();

        /* This hook runs long before the console or the screen exists, so the failure is
         * LATCHED and reported later. The vision fork's
         * __BKPT(0) is deleted, because a breakpoint with no debugger attached is a dead board
         * and a booth demo never stops at one.
         *
         * The Flexible Software Package copies .sdram_from_ospi0_cs1 AFTER this hook, so a
         * failure here costs both vision models and all the artwork as well as the story. That
         * is why the action is APP_DEGRADE_EXTERNAL and why all three of T_UI, T_AI and
         * T_STORY read this latch at their own start-up. */
        g_startup_ospi_err = err;

        if(FSP_SUCCESS != err)
        {
            ERROR_INDICATE_LED_ON;
        }

#if ENABLE_OSPI_8BIT_MODE
        // Important note: In order to use 8D-8D-8D, the data must be written with byte order swap in 16bit unit.
        //                 This project does not provide a solution. It is recommended to swap the data before programming by debugger
        /* The last __BKPT(0) in this file is deleted. It was unreachable -
         * ENABLE_OSPI_8BIT_MODE is (0) in src\application_config.h, and T_STORY makes this
         * switch itself, later, where it can report the failure - but no breakpoint is left on
         * an error path, and a dead one still has to be worked out by the next reader. LED3 is
         * kept. */
        err = ospi_b_set_protocol_to_opi();
        if(FSP_SUCCESS != err)
        {
            ERROR_INDICATE_LED_ON;
        }
#endif

#if defined(REQUIRE_OSPI_MEMORY_COPY_TO_SDRAM)
        // Note: Starting with FSPv6.0.0, the copy is done by Reset_Handler code.
#endif
#endif
    }
}
